python ./bin/data_mc_comparaison.py m_dilep 2016 "Dilepton mass (GeV)"
python ./bin/data_mc_comparaison.py m_dilep 2017 "Dilepton mass (GeV)"
python ./bin/data_mc_comparaison.py eta_elec 2016 "Electron #eta"
python ./bin/data_mc_comparaison.py eta_elec 2017 "Electron #eta"
python ./bin/data_mc_comparaison.py pt_elec 2016 "Electron p_{T} (GeV)"
python ./bin/data_mc_comparaison.py pt_elec 2017 "Electron p_{T} (GeV)"
python ./bin/data_mc_comparaison.py eta_muon 2016 "Muon #eta"
python ./bin/data_mc_comparaison.py eta_muon 2017 "Muon #eta"
python ./bin/data_mc_comparaison.py pt_muon 2016 "Muon p_{T} (GeV)"
python ./bin/data_mc_comparaison.py pt_muon 2017 "Muon p_{T} (GeV)"
python ./bin/data_mc_comparaison.py n_bjets 2016 "number of b-jets"
python ./bin/data_mc_comparaison.py n_bjets 2017 "number of b-jets"
python ./bin/data_mc_comparaison.py j1_pt 2016 "First jet p_{T} (GeV)"
python ./bin/data_mc_comparaison.py j1_pt 2017 "First jet p_{T} (GeV)"
python ./bin/data_mc_comparaison.py j1_eta 2016 "First jet #eta"
python ./bin/data_mc_comparaison.py j1_eta 2017 "First jet #eta"
python ./bin/data_mc_comparaison.py b1_pt 2016 "First b-jet p_{T} (GeV)"
python ./bin/data_mc_comparaison.py b1_pt 2017 "First b-jet p_{T} (GeV)"
python ./bin/data_mc_comparaison.py b1_eta 2016 "First b-jet #eta"
python ./bin/data_mc_comparaison.py b1_eta 2017 "First b-jet #eta"
python ./bin/data_mc_comparaison.py j2_pt 2016 "Second jet p_{T} (GeV)"
python ./bin/data_mc_comparaison.py j2_pt 2017 "Second jet p_{T} (GeV)"
python ./bin/data_mc_comparaison.py j2_eta 2016 "Second jet #eta"
python ./bin/data_mc_comparaison.py j2_eta 2017 "Second jet #eta"

